set(CMAKE_C_COMPILER   "clang${CLANG_VERSION}")
set(CMAKE_CXX_COMPILER "clang++${CLANG_VERSION}")
set(CMAKE_ASM_COMPILER "clang${CLANG_VERSION}")
set(CMAKE_C_LINKER     "clang${CLANG_VERSION}")
set(CMAKE_CXX_LINKER   "clang++${CLANG_VERSION}")

if(DEFINED CLANG_TRIPLE)
  set(CMAKE_C_COMPILER_TARGET   ${CLANG_TRIPLE})
  set(CMAKE_CXX_COMPILER_TARGET ${CLANG_TRIPLE})
  set(CMAKE_ASM_COMPILER_TARGET ${CLANG_TRIPLE})
endif()

if(DEFINED CLANG_SYSROOT)
  set(CMAKE_SYSROOT ${CLANG_SYSROOT})
endif()
  