set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(GCC_CROSS_COMPILE "aarch64-linux-gnu-")
set(GCC_VERSION "-10")
set(GCC_C_FLAGS_ADD -ffreestanding)
set(GCC_CXX_FLAGS_ADD -ffreestanding)
set(GCC_EXE_LINKER_FLAGS_ADD -nostdlib)
include(_gcc-common)
