set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(GCC_CROSS_COMPILE "aarch64-linux-gnu-")
set(GCC_VERSION "")
set(GCC_C_FLAGS_ADD -ffreestanding)
set(GCC_CXX_FLAGS_ADD )
set(GCC_EXE_LINKER_FLAGS_ADD -nostdlib)
include(_gcc-common)
